//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAiAssistant.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelAiAssistant.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 历史对话 的本地化字符串。
        /// </summary>
        internal static string ChatBox_btnHistory_Tips {
            get {
                return ResourceManager.GetString("ChatBox_btnHistory_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建对话 的本地化字符串。
        /// </summary>
        internal static string ChatBox_btnNewChat_Tips {
            get {
                return ResourceManager.GetString("ChatBox_btnNewChat_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string ChatBox_btnSend_Text {
            get {
                return ResourceManager.GetString("ChatBox_btnSend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送(Ctrl+Enter) 的本地化字符串。
        /// </summary>
        internal static string ChatBox_btnSend_Tips {
            get {
                return ResourceManager.GetString("ChatBox_btnSend_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新对话 的本地化字符串。
        /// </summary>
        internal static string ChatBox_Caption {
            get {
                return ResourceManager.GetString("ChatBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先配置模型参数！ 的本地化字符串。
        /// </summary>
        internal static string ChatBox_menuChangeModel_ErrorNote {
            get {
                return ResourceManager.GetString("ChatBox_menuChangeModel_ErrorNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExcelAI助手 的本地化字符串。
        /// </summary>
        internal static string ChatBox_Title {
            get {
                return ResourceManager.GetString("ChatBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        internal static string CodeEditor_Exec_Text {
            get {
                return ResourceManager.GetString("CodeEditor_Exec_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将代码保存在Excel中 的本地化字符串。
        /// </summary>
        internal static string CodeEditor_SaveCode_Text {
            get {
                return ResourceManager.GetString("CodeEditor_SaveCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块清理失败:  的本地化字符串。
        /// </summary>
        internal static string Component_Clean_Error {
            get {
                return ResourceManager.GetString("Component_Clean_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不符合Excel VBA代码规范，无法执行。 的本地化字符串。
        /// </summary>
        internal static string Component_DontComplyStandard {
            get {
                return ResourceManager.GetString("Component_DontComplyStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel COM 应用程序不可用。 的本地化字符串。
        /// </summary>
        internal static string Component_Excel_NotAvailable {
            get {
                return ResourceManager.GetString("Component_Excel_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行过程发生异常，请确认：
        ///1. 已启用VBA工程访问权限
        ///2. VBA代码语法正确
        ///
        ///异常信息： 的本地化字符串。
        /// </summary>
        internal static string Component_Exec_Error {
            get {
                return ResourceManager.GetString("Component_Exec_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加字典引用失败。 的本地化字符串。
        /// </summary>
        internal static string Component_Reference_Dict_Error {
            get {
                return ResourceManager.GetString("Component_Reference_Dict_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试一下下面的代码。 的本地化字符串。
        /// </summary>
        internal static string Component_TryCode {
            get {
                return ResourceManager.GetString("Component_TryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string FormAbout_Caption {
            get {
                return ResourceManager.GetString("FormAbout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V1.1.50401
        ///王珂作品
        ///hcling97@hotmail.com
        ///本软件遵循GPL3.0开源协议 的本地化字符串。
        /// </summary>
        internal static string FormAbout_Info {
            get {
                return ResourceManager.GetString("FormAbout_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/NixerWong/ExcelAiAssistant 的本地化字符串。
        /// </summary>
        internal static string FormAbout_Link {
            get {
                return ResourceManager.GetString("FormAbout_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel AI Assistant 的本地化字符串。
        /// </summary>
        internal static string FormAbout_SysName {
            get {
                return ResourceManager.GetString("FormAbout_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加模型 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_Caption {
            get {
                return ResourceManager.GetString("FormAddNewModel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用该模型 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_cbEnable {
            get {
                return ResourceManager.GetString("FormAddNewModel_cbEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口类型： 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_lbApiType {
            get {
                return ResourceManager.GetString("FormAddNewModel_lbApiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问密钥： 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_lbAppkey {
            get {
                return ResourceManager.GetString("FormAddNewModel_lbAppkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口地址： 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_lbBaseUrl {
            get {
                return ResourceManager.GetString("FormAddNewModel_lbBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型名称： 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_lbModelName {
            get {
                return ResourceManager.GetString("FormAddNewModel_lbModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提 示 词： 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_lbPrompt {
            get {
                return ResourceManager.GetString("FormAddNewModel_lbPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口地址是必填参数。 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_NoBaseUrl_Error {
            get {
                return ResourceManager.GetString("FormAddNewModel_NoBaseUrl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型名称是必填参数。 的本地化字符串。
        /// </summary>
        internal static string FormAddNewModel_NoModelName_Error {
            get {
                return ResourceManager.GetString("FormAddNewModel_NoModelName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新模型 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_btnAddNew {
            get {
                return ResourceManager.GetString("FormModelConfig_btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除模型 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_btnDelete {
            get {
                return ResourceManager.GetString("FormModelConfig_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确实要删除选中的模型么？ 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_btnDelete_Confirm {
            get {
                return ResourceManager.GetString("FormModelConfig_btnDelete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出模型 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_btnExport {
            get {
                return ResourceManager.GetString("FormModelConfig_btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入模型 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_btnImport {
            get {
                return ResourceManager.GetString("FormModelConfig_btnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数设置 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_Caption {
            get {
                return ResourceManager.GetString("FormModelConfig_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口类型 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_colApiType {
            get {
                return ResourceManager.GetString("FormModelConfig_colApiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口地址 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_colBaseUrl {
            get {
                return ResourceManager.GetString("FormModelConfig_colBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_colEnable {
            get {
                return ResourceManager.GetString("FormModelConfig_colEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型名称 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_colModelName {
            get {
                return ResourceManager.GetString("FormModelConfig_colModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Json 文件|*.json 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_Export_filter {
            get {
                return ResourceManager.GetString("FormModelConfig_Export_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出参数配置 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_Export_title {
            get {
                return ResourceManager.GetString("FormModelConfig_Export_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Json 文件|*.json 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_Import_filter {
            get {
                return ResourceManager.GetString("FormModelConfig_Import_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要导入的参数文件 的本地化字符串。
        /// </summary>
        internal static string FormModelConfig_Import_title {
            get {
                return ResourceManager.GetString("FormModelConfig_Import_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作确认 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Confirm {
            get {
                return ResourceManager.GetString("Global_Operation_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Copy {
            get {
                return ResourceManager.GetString("Global_Operation_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Delete {
            get {
                return ResourceManager.GetString("Global_Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Edit {
            get {
                return ResourceManager.GetString("Global_Operation_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Failure {
            get {
                return ResourceManager.GetString("Global_Operation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Paste {
            get {
                return ResourceManager.GetString("Global_Operation_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Save {
            get {
                return ResourceManager.GetString("Global_Operation_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_SelectAll {
            get {
                return ResourceManager.GetString("Global_Operation_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string Global_Operation_Success {
            get {
                return ResourceManager.GetString("Global_Operation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于程序 的本地化字符串。
        /// </summary>
        internal static string RibbonBtn_About {
            get {
                return ResourceManager.GetString("RibbonBtn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型设置 的本地化字符串。
        /// </summary>
        internal static string RibbonBtn_ModelConfig {
            get {
                return ResourceManager.GetString("RibbonBtn_ModelConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示助手 的本地化字符串。
        /// </summary>
        internal static string RibbonBtn_OpenBox {
            get {
                return ResourceManager.GetString("RibbonBtn_OpenBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel AI Assistant 的本地化字符串。
        /// </summary>
        internal static string RibbonTab_Title {
            get {
                return ResourceManager.GetString("RibbonTab_Title", resourceCulture);
            }
        }
    }
}
